development:  
  clients:    
    default:      
      database: my_app     
      hosts:
        - localhost:27017
      options:        
  options:    
    raise_not_found_error: false

<% if ENV['MONGOHQ_URL'] %>
  production:
    sessions:
      default:
        uri: <%= ENV['MONGOHQ_URL'] %>
        options:
          skip_version_check: true
          safe: true
<% end %>